openapi: "3.1.0"
info:
  title: "Demo API"
  description: "This is a demo API specification."
  version: 1.0.0
servers:
  - url: "http://example.com"
paths:
  /example:
    get:
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object