{
  "openapi": "3.1.0",
  "info": {
    "title": "Clearing",
    "description": "Partner API documentation for the Clearing services.",
    "contact": {
      "name": "Team Avregning"
    },
    "version": "11.7.0"
  },
  "externalDocs": {
    "description": "Clearing API Documentation",
    "url": "https://beta.developer.entur.no/partner/api/clearing/openapi-partner"
  },
  "servers": [
    {
      "url": "https://api.entur.io/clearing"
    },
    {
      "url": "https://api.staging.entur.io/clearing"
    },
    {
      "url": "https://api.dev.entur.io/clearing"
    },
    {
      "url": "http://localhost:8080"
    }
  ],
  "security": [
    {
      "bearerToken": []
    }
  ],
  "tags": [
    {
      "name": "Incoming Settlements",
      "description": "APIs for partners to create and manage settlements to be cleared by CLEOS"
    }
  ],
  "paths": {
    "/v1/settlement-import/generic": {
      "post": {
        "tags": [
          "Incoming Settlements"
        ],
        "summary": "Create Generic Settlement",
        "description": "TODO: UPDATE Creates a GenericSettlementImport, in queue for for clearing. Use the returned SettlementImportDTO for further queries",
        "operationId": "importGenericSettlement",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PartnerSettlementImportDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "409": {
            "description": "Conflict",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/CleosProblemJsonDto"
                }
              }
            }
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CleosProblemJsonDto": {
        "type": "object",
        "description": "DTO representing the generic response of an error condition according to the JSON+ERROR content type (RFC 9457).",
        "properties": {
          "type": {
            "type": "string",
            "format": "uri",
            "description": "URI identifying the type of problem. NOTE: type about:blank may still be used for general errors.",
            "enum": [
              "about:blank",
              "urn:problem-type:cleos-default",
              "urn:problem-type:cleos-ref"
            ],
            "example": "urn:problem-type:cleos-default"
          },
          "title": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "detail": {
            "type": "string"
          },
          "instance": {
            "type": "string",
            "format": "uri",
            "description": "Absolute URI to the the resource causing the error. Note that this is technically not a reference to the persistent error _instance_, but still useful default behaviour.",
            "example": "https://api.entur.io/clearing/v1/resource/123"
          },
          "properties": {
            "type": "object",
            "additionalProperties": {}
          },
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Server side timestamp of incident, used by cleos problem-types",
            "example": "2024-06-17T12:35:53.932Z"
          },
          "correlationId": {
            "type": "string",
            "description": "Correlation ID for tracking the error, used by cleos problem-types. Typically based on the request header X-Correlation-Id",
            "example": "1234-ABCDEFG-5678-HIJKL-91011-MNOPQ"
          },
          "domainRefs": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RefDto",
              "example": "EOS:Agreement:1234"
            }
          }
        }
      },
      "PartnerAnnexDto": {
        "type": "object",
        "description": "TODO: Annex representing a single Generic Annex.",
        "properties": {
          "type": {
            "type": "string"
          },
          "cancel": {
            "type": "boolean"
          },
          "guid": {
            "type": "string",
            "maxLength": 38,
            "minLength": 0
          },
          "annexRef": {
            "type": "string",
            "maxLength": 50,
            "minLength": 0
          },
          "attributes": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "price": {
            "$ref": "#/components/schemas/PartnerMoneyDto",
            "description": "PriceContribution may be provided if a custom weight is needed. The Amount will always be recalculated as the sum of PriceContributions."
          },
          "priceContribution": {
            "$ref": "#/components/schemas/PartnerMoneyDto"
          },
          "foreignAmount": {
            "$ref": "#/components/schemas/PartnerMoneyDto"
          },
          "description": {
            "type": "string",
            "maxLength": 500,
            "minLength": 0
          },
          "context": {
            "type": "object",
            "additionalProperties": {}
          },
          "parameters": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PartnerAnnexDto"
            }
          },
          "subAnnexes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PartnerAnnexDto"
            }
          }
        },
        "required": [
          "annexRef",
          "priceContribution"
        ]
      },
      "PartnerCommentDto": {
        "type": "object",
        "description": "Any external comments relevant for clearing the settlement. This will not be part of the reporting context",
        "properties": {
          "comment": {
            "type": "string",
            "maxLength": 500,
            "minLength": 0
          }
        },
        "required": [
          "comment"
        ]
      },
      "PartnerMoneyDto": {
        "type": "object",
        "description": "TODO: Representation of BigMoney (amount and currency) and Price (amount,currency and taxcode)",
        "properties": {
          "amount": {
            "type": "string"
          },
          "taxCode": {
            "type": "string"
          },
          "localTaxCode": {
            "type": "string"
          },
          "taxRate": {
            "type": "string"
          },
          "weight": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          }
        },
        "required": [
          "amount"
        ]
      },
      "PartnerSettlementImportDto": {
        "type": "object",
        "description": "TODO: Generic Incoming Settlement, this is a subset of values of SettlementImport without legacy values. If no SettlementNumber is specified, the next number in a negative sequence is used.",
        "properties": {
          "msgSubjectId": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "posRef": {
            "type": "string",
            "maxLength": 50,
            "minLength": 0
          },
          "distributionChannelRef": {
            "type": "string",
            "maxLength": 50,
            "minLength": 0
          },
          "settlementDate": {
            "type": "string",
            "format": "date"
          },
          "settlementNo": {
            "type": "integer",
            "format": "int64",
            "description": "Settlement Sequence Number. If not specified, the next number in a negative sequence is assigned based on successfully imported settlements on the same POS."
          },
          "correctionForSmntId": {
            "type": "integer",
            "format": "int64"
          },
          "externalSettlementNo": {
            "type": "integer",
            "format": "int64"
          },
          "comments": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PartnerCommentDto"
            }
          },
          "genericTransactions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PartnerTransactionImportDto"
            }
          },
          "context": {
            "type": "object",
            "additionalProperties": {}
          }
        },
        "required": [
          "distributionChannelRef",
          "posRef",
          "settlementDate"
        ]
      },
      "PartnerTransactionImportDto": {
        "type": "object",
        "description": "TODO: Incoming GenericTransaction containing GenericAnnexes.",
        "properties": {
          "transactionType": {
            "type": "string",
            "maxLength": 50,
            "minLength": 0
          },
          "orderId": {
            "type": "string",
            "maxLength": 50,
            "minLength": 0
          },
          "orderVersion": {
            "type": "integer",
            "format": "int32"
          },
          "genericAnnexes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PartnerAnnexDto"
            }
          }
        },
        "required": [
          "genericAnnexes",
          "transactionType"
        ]
      }
    },
    "securitySchemes": {
      "bearerToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}